apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-user1
  namespace: usuario-1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkinsuser1
  namespace: usuario-1
  labels:
    "app.kubernetes.io/name": "jenkins"
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding
  namespace: usuario-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkinsuser1
subjects:
  - kind: ServiceAccount
    name: usuario-1
    namespace: usuario-1
